language: ruby
before_install: "gem install rjack-tarpit -v'~>2.1' || \
      ( sleep 1; gem install rjack-tarpit -v'~>2.1' ) || \
      ( sleep 5; gem install rjack-tarpit -v'~>2.1' )"
bundler_args: ""
rvm:
  - jruby-1.7.24
  - jruby-9.0.5.0
  - jruby-head
script: "bundle exec rake test"
matrix:
  allow_failures:
    - rvm: jruby-head
