language: ruby
before_install:
  - "gem install rjack-tarpit -v=2.1.2"
  - "gem install bundler -v=1.17.3"
install: "bundle _1.17.3_ install --jobs=3 --retry=3"
sudo: false
script: "bundle exec rake test"
dist: trusty
matrix:
  include:
  - rvm: jruby-9.1.17.0
    jdk: openjdk8
  - rvm: jruby-9.2.5.0
    jdk: openjdk10
    dist: xenial
  - rvm: jruby-head
    jdk: openjdk10
    dist: xenial
  allow_failures:
    - rvm: jruby-head
