#!/bin/bash
#
# iyyov    Startup script for Iyyov monitoring daemon
#
# chkconfig: 2345 88 12
# description: Iyyov monitoring daemon
# processname: iyyov
# config: /opt/var/iyyov/jobs.rb

. /etc/rc.d/init.d/functions

# Gem home directory
# Set to match system "jgem environment path"
gem_home="/opt/jruby/gems"

# (Exact) Gem version of iyyov to run
version="1.3.0"

# User to run the daemon as (should own rundir)
user="iyyov"

# Running directory (for jobs.rb config, log, and pid file)
rundir="/opt/var/iyyov"

# Add PATH to jruby if non-standard
export PATH=/opt/bin:$PATH

prog="iyyov"
daemon="${gem_home}/gems/iyyov-${version}-java/init/${prog}"
config="${rundir}/jobs.rb"
pidfile="${rundir}/${prog}.pid"

RETVAL=0

start() {
    [ -x "$daemon" ] || exit 5
    [ -f "$config" ] || exit 6
    [ -d "$rundir" ] || exit 7

    echo -n $"Starting $prog: "
    runuser -c "cd $rundir && $daemon $config" $user
    RETVAL=$?
    [ $RETVAL -eq 0 ] && success $"$prog startup" || failure $"$prog startup"
    echo
}

status() {
    if [ -f "$pidfile" ]; then
        echo "Status $prog: running pid $(<$pidfile)"
    else
        echo "Status $prog: not running"
    fi
}

reload() {
    if [ -e "$pidfile" ]; then
        touch $config
    fi
}

stop() {
    echo -n $"Shutting down $prog: "
    killproc -p $pidfile $prog
    RETVAL=$?
    [ $RETVAL -eq 0 ] && success || failure
    echo
    return $RETVAL
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    reload)
        reload
        ;;
    restart)
        stop
        start
        RETVAL=$?
        ;;
    condrestart)
        [ -e $pidfile ] && restart
        RETVAL=$?
        ;;
    *)
        echo $"Usage: $0 {start|stop|status|reload|restart|condrestart}"
        RETVAL=1
esac

exit $RETVAL
